# Generated by Django 4.2.16 on 2025-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='upload_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='upload_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
