# Generated by Django 4.2.16 on 2025-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
