# Generated by Django 4.2.16 on 2025-06-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_pageimage_upload_error_pageimage_upload_response_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pageimage',
            name='crawler_pag_page_id_56cb07_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pageimage',
            unique_together=set(),
        ),
    ]
