# Generated by Django 4.2.16 on 2025-05-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_page_deleted_at_alter_pageimage_deleted_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageImage',
        ),
    ]
