# Generated by Django 4.2.16 on 2025-05-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_delete_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('file', models.FileField(upload_to='page_images/')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='crawler.page')),
            ],
            options={
                'indexes': [models.Index(fields=['page', 'url'], name='crawler_pag_page_id_56cb07_idx')],
                'unique_together': {('page', 'url')},
            },
        ),
    ]
