# Generated by Django 4.2.16 on 2025-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_pageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='markdown_content',
        ),
        migrations.AddField(
            model_name='page',
            name='markdown_file',
            field=models.FileField(null=True, upload_to='crawled_docs'),
        ),
    ]
